### PR TITLE
Implement frame layout

### PR DESCRIPTION
**Pull request by jfquevedol2198**
min-width: 90rem
image

max-width: 90rem
image

### CODE REVIEW

**Comment by meandrewandyou** [comment]
Peek 2023-10-20 18-24
X just lives it's separate life

**Comment by lietu** [comment]
> X just lives it's separate life

@meandrewandyou is there a design that makes you think it should behave otherwise?

**Comment by meandrewandyou** [comment]
> > X just lives it's separate life
> 
> @meandrewandyou is there a design that makes you think it should behave otherwise?

No, as far as there's no designs for different screen sizes. It's been said from user's POV

**Comment by lietu** [comment]
most users don't resize their screens and care too much about some element moving around - no design, not much we can do about it, and we've got limited time :smile:

**Review by lietu — APPROVED** [review]

**Pull request merged**
